### ISSUE TITLE
Language-based Security materials

### ISSUE THREAD

**Issue by sabelfeld** [delvedor/Language-Based-Security#1]
Hi Tomas,

This is Andrei Sabelfeld writing to you, I'm the instructor of the Language-based Security class at Chalmers http://www.cse.chalmers.se/edu/course/TDA602/

I've noticed that your repository is public.

Can you please remove it from public space as to ensure the integrity of the teaching materials?

Thanks,
-Andrei

**Comment by delvedor** [comment]
Hi Andrei, sure I can do it.
Can I just leave public the project part?

**Comment by sabelfeld** [comment]
Sure - thanks!

**Comment by Rawa** [comment]
@delvedor Note that you need to force push to remove all old course material. Right now the old commits are still present. 

https://github.com/delvedor/Language-Based-Security/commit/ffe3f3ad4b882360743681b4514c0dc5f307215e

**Comment by delvedor** [comment]
Sorry, I don't know how I can do that kind of remove.
If the `git rm folder/*` is ok for you, fine, otherwise please link me a good solution.

**Comment by sabelfeld** [comment]
Hi again! Looks like podak/Language-Based-Security is forked from here - can you please reach out to podak and ask podak to fetch changes from the parent repository, once they've been made?

I don't have a way of getting in touch with podak directly.

Thanks!

**Comment by delvedor** [comment]
Ok, I'll write to him.
